version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    env_file:
      - .env
  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      - 'redis_data:/bitnami'
    env_file:
      - .env
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:1.10.15
    env_file:
      - .env
    volumes:
      - airflow_scheduler_data:/bitnami
      - ${CUSTOM_DAGS_DIR}:/opt/bitnami/airflow/dags
      - ${CUSTOM_REQUIREMENTS}:/bitnami/python/requirements.txt
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:1.10.15
    env_file:
      - .env
    volumes:
      - airflow_worker_data:/bitnami
      - ${CUSTOM_DAGS_DIR}:/opt/bitnami/airflow/dags
      - ${CUSTOM_REQUIREMENTS}:/bitnami/python/requirements.txt
  airflow:
    image: docker.io/bitnami/airflow:1.10.15
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/bitnami
      - ${CUSTOM_DAGS_DIR}:/opt/bitnami/airflow/dags
      - ${CUSTOM_REQUIREMENTS}:/bitnami/python/requirements.txt
volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local
